<?xml version="1.0"?>
<package format="3">
  <name>factr2_w3_adapter</name><version>0.1.0</version>
  <description>Read-only standard messages for W3/NEXT</description>
  <maintainer email="dingyj@example.com">dingyj</maintainer><license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend><depend>rcl_interfaces</depend>
  <depend>sensor_msgs</depend><depend>diagnostic_msgs</depend>
  <exec_depend>launch</exec_depend><exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>rosgraph_msgs</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
