next_topic_root: /next/right
web:
  host: 127.0.0.1
  port: 8081
plot:
  max_points: 500
outputs:
  external_joint_torque: '{next_topic_root}/external_joint_torque'
  external_joint_torque_raw: '{next_topic_root}/external_joint_torque/raw'
  free_joint_torque_pred: '{next_topic_root}/free_joint_torque_pred'
  mse: '{next_topic_root}/mse'
  normalized_contact_magnitude: '{next_topic_root}/normalized_contact_magnitude'
  contact_state: '{next_topic_root}/contact_state'
contract_version: w3_next_v1
side: right
joint_names:
- right_joint_0
- right_joint_1
- right_joint_2
- right_joint_3
- right_joint_4
- right_joint_5
- right_joint_6
robot_topic_root: /factr2/right
